### ISSUE TITLE
Deprecate RenderableResource and fold it directly into ReadableResource

### ISSUE THREAD

**Issue by talios** [talios/halbuilder#10]

**Comment by jcassee** [comment]
Alright, I'll have a go at this one.

**Comment by jcassee** [comment]
I created a branch on my fork, `resource-refactor`. Please comment on my first attempt: jcassee/halbuilder@8e7ba8563ea7916ce49c3ff2f0cd497c7b9bd695

**Comment by talios** [comment]
Looks good for the most part - added some minor comments...

**Comment by jcassee** [comment]
I have a new revision for you to review. See:
https://github.com/jcassee/halbuilder/compare/resource-refactor

2012/4/18 Mark Derricutt
reply@reply.github.com:

> Looks good for the most part - added some minor comments...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/talios/halbuilder/issues/10#issuecomment-5195441

## 

Joost Cassee
http://joost.cassee.net

**Comment by jcassee** [comment]
By the way, I see that my use of Eclipse's Ctrl-O has rearranged the
import statements. Sorry about that!

2012/4/18 Joost Cassee joost@cassee.net:

> I have a new revision for you to review. See:
> https://github.com/jcassee/halbuilder/compare/resource-refactor
> 
> 2012/4/18 Mark Derricutt
> reply@reply.github.com:
> 
> > Looks good for the most part - added some minor comments...
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/talios/halbuilder/issues/10#issuecomment-5195441
> 
> ## 
> 
> Joost Cassee
> http://joost.cassee.net

## 

Joost Cassee
http://joost.cassee.net

**Comment by talios** [comment]
`public ImmutableResource read(Reader reader)` should probably still return the `ReadableResource` interface.  Other than that ( and the import changes ) I think that looks good..

**Comment by jcassee** [comment]
The latest changes in my branch address the import rearrangements and
the implementation of ReadableResource.read. Again see:
https://github.com/jcassee/halbuilder/compare/resource-refactor

If you are satisfied with the result I will merge it with my own
develop branch and send you a pull request.

**Comment by talios** [comment]
Looks good to me!  Pull request away ;-)

PS: Do you lurk on IRC or Twitter?  irc.freenode.org #rest or @talios here ;-)

**Comment by talios** [comment]
Released as 1.0.3 to Maven Central.
