### ISSUE TITLE
Name not set for curie link

### ISSUE THREAD

**Issue by jcassee** [talios/halbuilder#11]
Using halbuilder 1.0.1 from maven:
The example from the README file generates JSON that is missing the `name` attribute from the `curie` link. That means curie links cannot be resolved, right?

**Comment by jcassee** [comment]
Ah, the 1.0.2-SNAPSHOT contains a fix. So this issue should read: please release version 1.0.2. :-)

**Comment by talios** [comment]
I've been meaning to push out a new release - I'm away on holiday currently but returning home tomorrow, so will push out a release then.

Nice to see someone else using this :)

**Comment by jcassee** [comment]
Thanks!

Yeah, I was looking into halbuilder as a lightweight replacement for our current Jersey / Jackson / XML-to-JSON / schema-based monstrosity. Your project look much saner. :-)

**Comment by talios** [comment]
Heh thanks :) Halbuilder still uses Jackson under the covers to JSON generation. The HAL format also gives the added benefit of formalized <link>'s which closes a big hole in "REST" I've had for awhile.

**Comment by jcassee** [comment]
Great, thanks!
