### ISSUE TITLE
Question: using URIs for hrefs

### ISSUE THREAD

**Issue by jcassee** [talios/halbuilder#15]
Would you accept a pull request that adds versions of `ResourceFactory()` and `ResourceFactory.newResource()` that accept an `URI` instead of a `String`? (That would make interaction with Jersey slightly easier.)

**Comment by talios** [comment]
I don't see why not!  Thanks.  I've been thinking of renaming newResource(Reader) to readResource to make the distinction clearer between a new/empty resource, and one read from the network.

I assume your change is for new resources?   ( How does Jersey give you the URI? )

**Comment by jcassee** [comment]
Jersey generated URIs using its UriBuilder. For example:

``` java
@Path("/user/{id: [0-9]+}")
public class UserResource(@PathParam("id") Long id) {
    ...
}

...

URI uri = UriBuilder.fromResource(UserResource.class).build(user.getId());
```

Also, I create an absolute URI for the Jersey context root (= API root) using this code:

``` java
UriBuilder builder = UriBuilder.fromUri(request.getRequestURL().toString());
builder.replacePath(request.getContextPath());
builder.path(request.getServletPath());
URI rootUri = builder.build();
```

I will create a pull request with my proposed additions. If you want I can also start looking at some of the other todos, such as folding the RenderableResource into ReadableResource.

**Comment by talios** [comment]
Thanks! I was actually looking for a UriBuilder type class that handled UriTemplates - I wonder if Jersey's is in an artifact thats separate from the main project ( I use Restlet mostly ).

**Comment by talios** [comment]
PS: If you want to tackle the folding in RenderableResource into Readable that'd be awesome.  At this rate I might need to open a mailing list on Google Groups :)

**Comment by talios** [comment]
1.0.3 released and pushed to maven central.

Thanks for playing ;-)

**Comment by jcassee** [comment]
Thanks a lot!

**Comment by talios** [comment]
The Maven Central sync happens every hour so should turn up in a little while.
