### ISSUE TITLE
withLink() example backwards?

### ISSUE THREAD

**Issue by jamesladd** [talios/halbuilder#34]
In the README there is the example:

Resource owner = resourceFactory.newResource("http://example.com/mike")
  .withLink("td:friend", "http://example.com/mamund")

When I run this the resulting JSON looks like this:

{
    "_links":
    {
        "self":
        {
            "href":"http://localhost/api/..."
        },
        "http://example.com/mamund":
        {
            "href":"td:friend"
        }
    }
}

This looks wrong. However, when I switch the parameters around like this:

  .withLink("http://example.com/mamund", "td:friend")

Then I get a namespace error because 'td' is not defined.

When I remove the namespace prefix td: then all is ok.

So is the examples parameters around the wrong way??
- James.

**Comment by talios** [comment]
Hey James,

Good spotting.  Some time ago I switched the order of the parameters 
around and guess I missed some examples ( I fixed the tests but missed 
the README ).

I'm tempted to switch them over to taking a URL/URI rather than just a 
String, to make it more specific - thoughts?

Mark

**Comment by jamesladd** [comment]
Hi Mark,

I really like where you are going with the HalBuilder and it has got me off
to a good start with my project. Thanks!

I think a withLink(); that takes a URI/URL is useful - however I find that
since you do
such a good job handling relative URL's the use of URI/URL might be more
painful
than a String.

That being said, you are building a library so supporting both would be the
most useful,
although more work.

Rgs, James.

On Tue, Jun 19, 2012 at 2:58 PM, Mark Derricutt <
reply@reply.github.com
