### ISSUE TITLE
Not getting template=true

### ISSUE THREAD

**Issue by jamesladd** [talios/halbuilder#37]
I have a template URI and when I render the document the link doesn't have template=true.
Am I correct in thinking this was automatic in HalBuilder when a URI has a param? 

Here is my code snippet:

```
    Optional<String> name = Optional.absent();
    Optional<String> title = Optional.of("Product Search");
    Optional<String> hreflang = Optional.absent();
    resource.withLink("/api/products{?query}", "products", 
                 Optional.<Predicate<ReadableResource>>absent(), name, title, hreflang);
```

When rendered:

 "products" : {
      "href" : "http://localhost:8080/api/products{?query}",
      "title" : "Product Search"
    }

I expected:

 "products" : {
      "href" : "http://localhost:8080/api/products{?query}",
      "title" : "Product Search",
      "templated" : true
    }

**Comment by jamesladd** [comment]
Works fine in 1.0.5

**Comment by jamesladd** [comment]
1.0.5

**Comment by talios** [comment]
You mean 1.0.5-SNAPSHOT I guess, UriTemplate support hasn't been released yet ( I thought I had made that release but obviously not! ).

Will get that released soon :)

**Comment by jamesladd** [comment]
BTW - How can I build a URI with a Template?
I try UriBuilder but always get the URL encoded.
ie: {?query} becomes %7B%3Fquery%7D

On Wed, Jun 20, 2012 at 6:24 PM, Mark Derricutt <
reply@reply.github.com

**Comment by talios** [comment]
James,

How are you using this in your code? If you use { and } inside a URI 
then yes, they will be URL encoded. A UriTemplate isn't actually a valid 
URI so you'll need to add that as a String.

I think its about time I wrote up some form of user guide :-)

**Comment by jamesladd** [comment]
I tried

UriBuilder.fromUri(baseURI()).path("/api{arg}").build("{?query}");

it gets encoded.

On Wed, Jun 20, 2012 at 8:26 PM, Mark Derricutt <
reply@reply.github.com

**Comment by talios** [comment]
On 20/06/12 10:36 PM, James Ladd wrote:

> I tried
> 
> UriBuilder.fromUri(baseURI()).path("/api{arg}").build("{?query}");
> 
> it gets encoded.
> 
> the .build() method your calling there takes a vararg of Object, from 
> quick experimentation it seems that the Object#toString is called and 
> replaced with nth template argument, i.e.

   UriBuilder.fromUri(baseURI()).path("/api/{arg}").build(1234);

  yeilds "/api/1234".  I'm normally using buildFromMap() ( as used in 
the tests ):

URI path = 
UriBuilder.fromPath("customer/{id}").buildFromMap(ImmutableMap.of("id", 
"123456"));

Interestingly, I just tried using {?id} in a template and UriBuilder ( 
at least the version from Jersey 1.13-b01 ) failed to actually validate 
the template.

The DamnHandy UriTemplate library seems the best to me, which is 
independent of any rest framework:

   https://github.com/damnhandy/Handy-URI-Templates

```
     String uri = 
```

com.damnhandy.uri.template.UriTemplate.fromExpression("/customer/phone{?id,number}")
                 .set("id", phone.getId())
                 .set("number", phone.getNumber())
                 .expand();

This still encodes however, this actually looks to be a bug in 
HalBuilder when I'm resolving the relative/absolute URI into a canonical 
full URI with http://xxxx included.

**Comment by talios** [comment]
On 20/06/12 10:36 PM, James Ladd wrote:

> it gets encoded.

The remaining encoding I see only occurs in the XML representation which 
is actually expected and the ampersand character denotes an entity 
reference in XML, thus needs to be escaped.
