### ISSUE TITLE
withNamespace() example problem

### ISSUE THREAD

**Issue by g3cco** [talios/halbuilder#45]
In the halbuilder-core.README there is the example:

```
    Representation halResource = representationFactory.newRepresentation("http://example.com/todo-list")
      .withNamespace("td", "http://example.com/todoapp/rels/")
```

...

When I try to run this example I am getting following error:

Exception in thread "main" com.theoryinpractise.halbuilder.api.RepresentationException: Namespace 'td' does not include {rel} URI template argument.
    at com.theoryinpractise.halbuilder.impl.representations.NamespaceManager.withNamespace(NamespaceManager.java:26)

I am missing anything here?
What is the role of withNamespace() here?

Thank you,

Igor

**Comment by talios** [comment]
Igor,

In line with all the examples I've seen in the spec, CURIE'd URIs are template URIs which include a `{rel}` attribute which is to be replaced with the rel content found _after_ a `:`.

As such, a link or embedded resource with a rel of `myapp:example` would be resolved against a link in the representation such as:

```
{
  _links: {
    "curie": { href: "http://somewhere/rels/{rel}", name: "myapp", templated: true}
  }
}
```

This would then get resolved to `http://somewhere/rels/example`.

On the flip side, when you add any link or embedded representation with a rel such as `http://somewhere/rels/anotherexample` it should be rendered as `myapp:anotherexample` assuming the CURIE/namespace has been configured.

**Comment by g3cco** [comment]
Thanks for the explanation and a fast response.

It seems to me there is a typo in the halbuilder-core.README.md example:  
instead of:

.withNamespace("td", "http://example.com/todoapp/rels/")

it should be:

.withNamespace("td", "http://example.com/todoapp/{rel}")

end then the error is gone.

**Comment by talios** [comment]
Cheers, README.md updated - I'm also working on updating the main gotohal.net documentation as well, which is sadly now out of date slightly as well.
