### ISSUE TITLE
MutableRepresentation.withBean() serializes hashCode() method

### ISSUE THREAD

**Issue by keki007** [talios/halbuilder#46]
withBean(Object value) calls findPropertyReadMethod(methodName) does a pattern match:

Pattern.compile("^(get|is|has)(.+)$");

This match matches on the following method signature:

public native int java.lang.Object.**has**hCode();

So a property called hCode is returned.

**Comment by talios** [comment]
ah! my bad.   I should add hashCode and equals to the method exclusion list along with getClass.  WIll roll a fix/release tonight!

**Comment by talios** [comment]
This is now fixed on halbuilder-core 4.0.6, note that the project is actually now at `https://github.com/halbuilder/halbuilder-core` on the `support/4.x` branch.
